spring:
  application:
    name: backend
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/mystreak?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
